import {
  problemCatalog,
  problemJsonContentType,
  problemTypeBaseUrl
} from "./problem.js";

export const requestIdHeaderName = "x-request-id" as const;

const problemCodes = Object.keys(problemCatalog);
const problemTypes = problemCodes.map((code) => `${problemTypeBaseUrl}/${code}`);

export const openApiDocument = {
  openapi: "3.1.0",
  jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
  info: {
    title: "Vind API",
    version: "0.1.0"
  },
  paths: {
    "/api/v1/health/live": {
      get: {
        operationId: "getLiveHealth",
        tags: ["Health"],
        responses: {
          "200": {
            description: "The API process is live.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/LiveHealth"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/health/ready": {
      get: {
        operationId: "getReadyHealth",
        tags: ["Health"],
        responses: {
          "200": {
            description: "The API and required dependencies are ready.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/ReadyHealth"
                }
              }
            }
          },
          "503": {
            $ref: "#/components/responses/Problem"
          }
        }
      }
    },
    "/api/v1/openapi.json": {
      get: {
        operationId: "getOpenApiDocument",
        tags: ["OpenAPI"],
        responses: {
          "200": {
            description: "The OpenAPI 3.1 document.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  type: "object"
                }
              }
            }
          }
        }
      }
    }
  },
  components: {
    headers: {
      RequestId: {
        description: "Request correlation identifier generated by the API or propagated from a valid x-request-id header.",
        schema: {
          $ref: "#/components/schemas/RequestId"
        }
      }
    },
    responses: {
      Problem: {
        description: "A problem response.",
        headers: {
          "x-request-id": {
            $ref: "#/components/headers/RequestId"
          }
        },
        content: {
          [problemJsonContentType]: {
            schema: {
              $ref: "#/components/schemas/ProblemDetails"
            }
          }
        }
      }
    },
    schemas: {
      RequestId: {
        type: "string",
        minLength: 8,
        maxLength: 128,
        pattern: "^[A-Za-z0-9._:-]+$"
      },
      LiveHealth: {
        type: "object",
        required: ["status"],
        properties: {
          status: {
            const: "live"
          }
        },
        additionalProperties: false
      },
      ReadyHealth: {
        type: "object",
        required: ["status", "dependencies"],
        properties: {
          status: {
            const: "ready"
          },
          dependencies: {
            type: "array",
            items: {
              $ref: "#/components/schemas/DependencyReadiness"
            }
          }
        },
        additionalProperties: false
      },
      DependencyReadiness: {
        type: "object",
        required: ["name", "status"],
        properties: {
          name: {
            type: "string"
          },
          status: {
            enum: ["ready", "down"]
          }
        },
        additionalProperties: false
      },
      ProblemDetails: {
        type: "object",
        required: ["type", "title", "status", "code", "requestId", "instance"],
        properties: {
          type: {
            enum: problemTypes
          },
          title: {
            type: "string"
          },
          status: {
            type: "integer",
            minimum: 400,
            maximum: 599
          },
          code: {
            enum: problemCodes
          },
          requestId: {
            $ref: "#/components/schemas/RequestId"
          },
          instance: {
            type: "string"
          },
          detail: {
            type: "string"
          }
        },
        additionalProperties: true
      }
    }
  }
} as const;

export type OpenApiDocument = typeof openApiDocument;
