import {
  problemCatalog,
  problemJsonContentType,
  problemTypePrefix
} from "./problem.js";

export const requestIdHeaderName = "x-request-id" as const;

const problemCodes = Object.keys(problemCatalog);
const problemTypes = problemCodes.map((code) => `${problemTypePrefix}${code}`);

export const openApiDocument = {
  openapi: "3.1.0",
  jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema",
  info: {
    title: "Vind API",
    version: "0.1.0"
  },
  paths: {
    "/api/v1/health/live": {
      get: {
        operationId: "getLiveHealth",
        tags: ["Health"],
        responses: {
          "200": {
            description: "The API process is live.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/LiveHealthEnvelope"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/health/ready": {
      get: {
        operationId: "getReadyHealth",
        tags: ["Health"],
        responses: {
          "200": {
            description: "The API and required dependencies are ready.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/ReadyHealthEnvelope"
                }
              }
            }
          },
          "503": {
            $ref: "#/components/responses/Problem"
          }
        }
      }
    },
    "/api/v1/openapi.json": {
      get: {
        operationId: "getOpenApiDocument",
        tags: ["OpenAPI"],
        responses: {
          "200": {
            description: "The OpenAPI 3.1 document.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  type: "object"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/me": {
      get: {
        operationId: "getAuthenticatedContext",
        tags: ["Session"],
        summary: "Get authenticated context and presentation details",
        security: [{ cookieAuth: [] }],
        responses: {
          "200": {
            description: "Authenticated actor context.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/AuthenticatedContextEnvelope"
                }
              }
            }
          },
          "401": {
            $ref: "#/components/responses/Problem"
          }
        }
      }
    },
    "/api/v1/session/logout": {
      post: {
        operationId: "logoutSession",
        tags: ["Session"],
        summary: "Revoke session and clear authentication context",
        security: [{ cookieAuth: [] }],
        responses: {
          "200": {
            description: "Session successfully revoked.",
            headers: {
              "x-request-id": {
                $ref: "#/components/headers/RequestId"
              }
            },
            content: {
              "application/json": {
                schema: {
                  $ref: "#/components/schemas/LogoutEnvelope"
                }
              }
            }
          },
          "401": {
            $ref: "#/components/responses/Problem"
          }
        }
      }
    }
  },
  components: {
    securitySchemes: {
      cookieAuth: {
        type: "apiKey",
        in: "cookie",
        name: "vind_session",
        description: "Server-side opaque session token stored in an HttpOnly cookie."
      }
    },
    headers: {
      RequestId: {
        description: "Request correlation identifier generated by the API or propagated from a valid x-request-id header.",
        schema: {
          $ref: "#/components/schemas/RequestId"
        }
      }
    },
    responses: {
      Problem: {
        description: "A problem response.",
        headers: {
          "x-request-id": {
            $ref: "#/components/headers/RequestId"
          }
        },
        content: {
          [problemJsonContentType]: {
            schema: {
              $ref: "#/components/schemas/ProblemDetails"
            }
          }
        }
      }
    },
    schemas: {
      RequestId: {
        type: "string",
        minLength: 8,
        maxLength: 128,
        pattern: "^[A-Za-z0-9._:-]+$"
      },
      LiveHealth: {
        type: "object",
        required: ["status"],
        properties: {
          status: {
            const: "live"
          }
        },
        additionalProperties: false
      },
      ReadyHealth: {
        type: "object",
        required: ["status"],
        properties: {
          status: {
            const: "ready"
          }
        },
        additionalProperties: false
      },
      ResponseMeta: {
        type: "object",
        required: ["request_id"],
        properties: {
          request_id: {
            $ref: "#/components/schemas/RequestId"
          }
        },
        additionalProperties: false
      },
      LiveHealthEnvelope: {
        type: "object",
        required: ["data", "meta"],
        properties: {
          data: {
            $ref: "#/components/schemas/LiveHealth"
          },
          meta: {
            $ref: "#/components/schemas/ResponseMeta"
          }
        },
        additionalProperties: false
      },
      ReadyHealthEnvelope: {
        type: "object",
        required: ["data", "meta"],
        properties: {
          data: {
            $ref: "#/components/schemas/ReadyHealth"
          },
          meta: {
            $ref: "#/components/schemas/ResponseMeta"
          }
        },
        additionalProperties: false
      },
      ProblemDetails: {
        type: "object",
        required: ["type", "title", "status", "code", "request_id", "retryable", "instance"],
        properties: {
          type: {
            enum: problemTypes
          },
          title: {
            type: "string"
          },
          status: {
            type: "integer",
            minimum: 400,
            maximum: 599
          },
          code: {
            enum: problemCodes
          },
          request_id: {
            $ref: "#/components/schemas/RequestId"
          },
          retryable: {
            type: "boolean"
          },
          instance: {
            type: "string"
          },
          detail: {
            type: "string"
          },
          field_errors: {
            type: "array",
            items: {
              $ref: "#/components/schemas/FieldError"
            }
          }
        },
        additionalProperties: true
      },
      FieldError: {
        type: "object",
        required: ["field", "code"],
        properties: {
          field: {
            type: "string"
          },
          code: {
            type: "string"
          },
          message: {
            type: "string"
          }
        },
        additionalProperties: false
      },
      ChannelSummary: {
        type: "object",
        required: ["code", "name"],
        properties: {
          code: { type: "string" },
          name: { type: "string" }
        },
        additionalProperties: false
      },
      AuthenticatedContext: {
        type: "object",
        required: ["actor_kind", "authority_plane", "account_key", "channel"],
        properties: {
          actor_kind: { enum: ["HUMAN", "SERVICE"] },
          authority_plane: { enum: ["RELATIONSHIP", "LOCAL", "PLATFORM", "SERVICE"] },
          account_key: { type: "string" },
          person_key: { type: "string" },
          channel: { $ref: "#/components/schemas/ChannelSummary" },
          membership_key: { type: "string" },
          local_assignment_key: { type: "string" },
          platform_assignment_key: { type: "string" },
          service_grant_key: { type: "string" },
          organization_key: { type: "string" },
          workspace_key: { type: "string" },
          provider_key: { type: "string" },
          region_key: { type: "string" }
        },
        additionalProperties: false
      },
      AuthenticatedContextEnvelope: {
        type: "object",
        required: ["data", "meta"],
        properties: {
          data: { $ref: "#/components/schemas/AuthenticatedContext" },
          meta: { $ref: "#/components/schemas/ResponseMeta" }
        },
        additionalProperties: false
      },
      LogoutResult: {
        type: "object",
        required: ["success"],
        properties: {
          success: { type: "boolean" }
        },
        additionalProperties: false
      },
      LogoutEnvelope: {
        type: "object",
        required: ["data", "meta"],
        properties: {
          data: { $ref: "#/components/schemas/LogoutResult" },
          meta: { $ref: "#/components/schemas/ResponseMeta" }
        },
        additionalProperties: false
      }
    }
  }
} as const;

export type OpenApiDocument = typeof openApiDocument;
